# Generated by Django 4.2.2 on 2023-06-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_transaction_transactionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.product'),
        ),
    ]
